DROP DATABASE IF EXISTS chatProject;
CREATE DATABASE chatProject;
USE chatProject;

CREATE TABLE utenti (
    IDutente BIGINT UNSIGNED PRIMARY KEY,
    nome VARCHAR(20) BINARY NOT NULL,
    cognome VARCHAR(100) BINARY NOT NULL,
    nickname VARCHAR(50) BINARY NOT NULL,
    dataCreazione DATE NOT NULL,
    CONSTRAINT CHK_IDUTENTE_10_DIGITS CHECK (IDutente BETWEEN 1000000000 AND 9999999999)
);

CREATE TABLE chat (
    IDchat BIGINT UNSIGNED PRIMARY KEY,
    utente1 BIGINT UNSIGNED,
    utente2 BIGINT UNSIGNED,
    CONSTRAINT FK_UTENTE1 FOREIGN KEY (utente1) REFERENCES utenti(IDutente),
    CONSTRAINT FK_UTENTE2 FOREIGN KEY (utente2) REFERENCES utenti(IDutente),
    CONSTRAINT CHK_IDCHAT_10_DIGITS CHECK (IDchat BETWEEN 1000000000 AND 9999999999)
);

CREATE TABLE messaggi (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    textmessage VARCHAR(15000) NOT NULL,
    senderID BIGINT UNSIGNED,
    reciverID BIGINT UNSIGNED,
    timenow DATETIME NOT NULL,
    CONSTRAINT FK_SENDER FOREIGN KEY (senderID) REFERENCES utenti(IDutente),
    CONSTRAINT FK_RECEIVER FOREIGN KEY (reciverID) REFERENCES utenti(IDutente),
    CONSTRAINT CHK_SENDER_10_DIGITS CHECK (senderID BETWEEN 1000000000 AND 9999999999),
    CONSTRAINT CHK_RECEIVER_10_DIGITS CHECK (reciverID BETWEEN 1000000000 AND 9999999999)
);
