DROP DATABASE IF EXISTS chatProject;
CREATE DATABASE chatProject;
USE chatProject;

CREATE TABLE utenti (
    IDutente INT ZEROFILL UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(20) BINARY NOT NULL,
    cognome VARCHAR(100) BINARY NOT NULL,
    nickname VARCHAR(50) BINARY NOT NULL,
    dataCreazione DATE NOT NULL
);

CREATE TABLE chat (
    IDchat INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    utente1 INT ZEROFILL UNSIGNED,
    utente2 INT ZEROFILL UNSIGNED,
    CONSTRAINT FK_UTENTE1 FOREIGN KEY (utente1) REFERENCES utenti(IDutente),
    CONSTRAINT FK_UTENTE2 FOREIGN KEY (utente2) REFERENCES utenti(IDutente)
);

CREATE TABLE messaggi (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    textmessage VARCHAR(15000) NOT NULL,
    senderID INT ZEROFILL UNSIGNED,
    reciverID INT ZEROFILL UNSIGNED,
    timenow DATETIME NOT NULL,
    CONSTRAINT FK_SENDER FOREIGN KEY (senderID) REFERENCES utenti(IDutente),
    CONSTRAINT FK_RECEIVER FOREIGN KEY (reciverID) REFERENCES utenti(IDutente)
);